package fortuna.models.competition;

public enum FootballCompetition implements EventCompetition {

    /* EUROPE */
    CHAMPIONS_LEAGUE,
    EUROPA_LEAGUE,
    CONFERENCE_LEAGUE,

    /* ENGLAND */
    PREMIER_LEAGUE,
    CHAMPIONSHIP,
    FA_CUP,
    LEAGUE_CUP,
    LEAGUE_ONE,
    LEAGUE_TWO,

    /* ITALY */
    SERIE_A,
    SERIE_B,
    COPPA_ITALIA,

    /* SPAIN */
    LA_LIGA,
    LA_LIGA_2,
    COPA_DEL_REY,

    /* FRANCE */
    LIGUE_1,
    LIGUE_2,
    COUPE_DE_FRANCE,

    /* GERMANY */
    BUNDESLIGA,
    BUNDESLIGA_2,
    DFB_POKAL,

    /* TURKEY */
    SUPER_LIG_TURKEY,
    TURKEY_LEAGUE_2,
    TURKEY_CUP,

    /* PORTUGAL */
    PRIMIERA_LIGA_PORTUGAL,
    PORTUGAL_LEAGUE_2,
    PORTUGAL_CUP,

    /* NETHERLANDS */
    EVERDISIE,
    EERSTE_DIVISIE,
    KNVB_CUP,

    /* AUSTRIA */
    AUSTRIA_LEAGUE_1,
    AUSTRIA_LEAGUE_2,
    AUSTRIA_OFB_CUP,

    /* SWITZERLAND */
    SWITZERLAND_SUPER_LEAGUE_1,
    SWITZERLAND_CHALLENGE_LEAGUE_2,
    SWITZERLAND_PROMOTION_LEAGUE_3,

    /* BELGIUM */
    BELGIUM_FIRST_DIVISION_A_1,
    BELGIUM_FIRST_DIVISION_B_2,
    BELGIUM_CUP,

    /* BULGARIA */
    BULGARIA_LEAGUE_1,
    BULGARIA_LEAGUE_2,

    /* CROATIA */
    CROATIA_LEAGUE_1,
    CROATIA_LEAGUE_2,

    /* CYPRUS */
    CYPRUS_LEAGUE_1,

    /* CZECH REPUBLIC */
    CZECH_REPUBLIC_LEAGUE_1,
    CZECH_REPUBLIC_LEAGUE_2,
    CZECH_REPUBLIC_CUP,

    /* DENMARK */
    DENMARK_LEAGUE_1,
    DENMARK_LEAGUE_2,
    DENMARK_CUP,

    /* GREECE */
    GREECE_LEAGUE_1,
    GREECE_LEAGUE_2,

    /* IRELAND */
    IRELAND_LEAGUE_1,
    IRELAND_LEAGUE_2,

    /* ISRAEL */
    ISRAEL_LEAGUE_1,

    /* MALTA */
    MALTA_CUP,

    /* NORWAY */
    NORWAY_LEAGUE_1,
    NORWAY_LEAGUE_2,

    /* POLAND */
    POLAND_LEAGUE_1,
    POLAND_LEAGUE_2,
    POLAND_CUP,

    /* SCOTLAND */
    SCOTLAND_PREMIER_LEAGUE,
    SCOTLAND_CHAMPIONSHIP,
    SCOTLAND_FA_CUP,
    SCOTLAND_LEAGUE_ONE,
    SCOTLAND_LEAGUE_TWO,

    /* SWEDEN */
    SWEDEN_LEAGUE_1,
    SWEDEN_LEAGUE_2,
    SWEDEN_CUP,

    /* UKRAINE */
    UKRAINE_LEAGUE_1,

    /* ARGENTINA */
    ARGENTINA_LEAGUE_1,
    ARGENTINA_LEAGUE_2,

    /* BRAZIL */
    BRAZIL_LEAGUE_1,
    BRAZIL_LEAGUE_2,

    /* USA */
    MLS,

    /* JAPAN */
    JAPAN_LEAGUE_1,
    JAPAN_LEAGUE_2,
    JAPAN_LEAGUE_3


}
