package fortuna.models.competition;

public enum FootballCompetition implements EventCompetition {

    /* EUROPE */
    CHAMPIONS_LEAGUE,
    EUROPA_LEAGUE,
    CONFERENCE_LEAGUE,

    /* ENGLAND */
    PREMIER_LEAGUE,
    CHAMPIONSHIP,
    FA_CUP,
    LEAGUE_CUP,
    LEAGUE_ONE,
    LEAGUE_TWO,

    /* ITALY */
    SERIE_A,
    SERIE_B,
    COPPA_ITALIA,

    /* SPAIN */
    LA_LIGA,
    LA_LIGA_2,
    COPA_DEL_REY,

    /* FRANCE */
    LIGUE_1,
    LIGUE_2,
    COUPE_DE_FRANCE,

    /* GERMANY */
    BUNDESLIGA,
    BUNDESLIGA_2,
    DFB_POKAL,

    /* TURKEY */
    SUPER_LIG_TURKEY,

    /* PORTUGAL */
    PRIMIERA_LIGA_PORTUGAL,

    /* NETHERLANDS */
    EVERDISIE,
    EERSTE_DIVISIE,
    KNVB_CUP,

    /* AUSTRIA */
    AUSTRIA_BUNDESLIGA_CHAMPIONS_GROUP,
    AUSTRIA_BUNDESLIGA_RELEGATION_GROUP,
    AUSTRIA_LIGA_2,
    AUSTRIA_OFB_CUP,

    /* SWITZERLAND */
    SWITZERLAND_SUPER_LEAGUE_1,
    SWITZERLAND_CHALLENGE_LEAGUE_2,
    SWITZERLAND_PROMOTION_LEAGUE_3,

    /* BELGIUM */
    BELGIUM_FIRST_DIVISION_A_1,
    BELGIUM_FIRST_DIVISION_B_2,
    BELGIUM_CUP,

    /* BULGARIA */
    BULGARIA_LEAGUE_1,
    BULGARIA_LEAGUE_2,

    /* CROATIA */
    CROATIA_LEAGUE_1,

    /* CYPRUS */
    CYPRUS_LEAGUE_1,

    /* CZECH REPUBLIC */
    CZECH_REPUBLIC_LEAGUE_1,
    CZECH_REPUBLIC_LEAGUE_2,
    CZECH_REPUBLIC_CUP,

    /* DENMARK */
    DENMARK_LEAGUE_1,
    DENMARK_LEAGUE_2

}
